/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_cardcontact_jni2ctapi_cardterminal_0005fapi */

#ifndef _Included_de_cardcontact_jni2ctapi_cardterminal_0005fapi
#define _Included_de_cardcontact_jni2ctapi_cardterminal_0005fapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_cardcontact_jni2ctapi_cardterminal_0005fapi
 * Method:    CT_Init
 * Signature: (CC)I
 */
JNIEXPORT jint JNICALL Java_de_cardcontact_jni2ctapi_cardterminal_1api_CT_1Init
  (JNIEnv *, jobject, jchar, jchar);

/*
 * Class:     de_cardcontact_jni2ctapi_cardterminal_0005fapi
 * Method:    CT_Close
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_de_cardcontact_jni2ctapi_cardterminal_1api_CT_1Close
  (JNIEnv *, jobject, jchar);

/*
 * Class:     de_cardcontact_jni2ctapi_cardterminal_0005fapi
 * Method:    CT_Data
 * Signature: (CBBI[BC[B)I
 */
JNIEXPORT jint JNICALL Java_de_cardcontact_jni2ctapi_cardterminal_1api_CT_1Data
  (JNIEnv *, jobject, jchar, jbyte, jbyte, jint, jbyteArray, jchar, jbyteArray);

/*
 * Class:     de_cardcontact_jni2ctapi_cardterminal_0005fapi
 * Method:    setReader
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_cardcontact_jni2ctapi_cardterminal_1api_setReader
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
